import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col justify-between px-24">
          <div className="mt-8 flex flex-col items-center justify-center gap-12">
            <div className="flex w-[428px] flex-col items-center rounded-3xl bg-slate-100 p-4">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
